### ISSUE TITLE
Open discussion about Kytos UI

### ISSUE THREAD

**Issue by Niehaus** [kytos/ui#65]
Hello, guys, here you can feel free to discuss anything you want about our Kytos UI. It is highly recommended:

1. To post printscreen images for better visualization about what you are talking if needed;
2. If you got an error try to let us know how to reproduce it, and please inform wich browser you're using; 
3. If you're not confortable with open an issue you can always ask something in our slack channels, or directly;
4. Suggestions are always welcome and you are too!

**Comment by beraldoleal** [comment]
Hi, @Niehaus I think is nice to have a place do discuss ideas, and we should do it more often and transparent, so thanks for the initiative here.

But instead of having one big issue, to discuss multiple items, IMO it is better for tracking if we have one issue per topic. So I'm not sure if this makes sense. Having individual issues or feature requests would be better. In that way, we can track better the progress.

I'm just afraid of having here to many topic to discuss in a such generic thread.

Also, the idea of an issue is that we could have a life-cycle with one final goal: close the issue. This kind of issue seems to me that will never be closed. Yes, we have an 'epic' tag for big issues, but the idea is the same: to close the issue at the end.

IMO, the best place to discuss ideas is on #kytos-ui channel, then we move to issues or blueprints individual ones.

Maybe we need to improve our contributor guide to redirect to the proper channel (issue, slack, or blueprint) when users are having problems or they have feature requests.

What do you think?

**Comment by Niehaus** [comment]
Hi @beraldoleal, yes, you're right, but  the main idea for this 'issue' to exist is because on the meeting that we had with the students, Vasi talked about they show us some demo in the next meeting. So, to help us/me with new examples of usage I thought about open this issue for general discussion and for show some of the examples with prints and code, it includes me as well.

**Comment by beraldoleal** [comment]
I see, but still not sure if one generic issue is the best place.

GH Issues are not a forum. Each topic, each issue should be in one specific issue.

They demos are about one specifc napp ? Or about multiple napps?

**Comment by Niehaus** [comment]
Sorry for the late answer, I really give it a thought, so now I see what is your point, and you're right, thank you for that! And about  our Submission Guide Line it really should be on the README.. I'll do a PR about that and we can close this issue.

**Comment by hdiogenes** [comment]
GitHub just launched a new "Discussions" feature just for this, @Niehaus. I've just enabled it on the UI project: https://github.com/kytos/ui/discussions/
